TEAM_INFO = {
    "ATL": ("Atlanta Hawks", "East", "Southeast"),
    "BOS": ("Boston Celtics", "East", "Atlantic"),
    "BKN": ("Brooklyn Nets", "East", "Atlantic"),
    "CHA": ("Charlotte Hornets", "East", "Southeast"),
    "CHI": ("Chicago Bulls", "East", "Central"),
    "CLE": ("Cleveland Cavaliers", "East", "Central"),
    "DAL": ("Dallas Mavericks", "West", "Southwest"),
    "DEN": ("Denver Nuggets", "West", "Northwest"),
    "DET": ("Detroit Pistons", "East", "Central"),
    "GSW": ("Golden State Warriors", "West", "Pacific"),
    "HOU": ("Houston Rockets", "West", "Southwest"),
    "IND": ("Indiana Pacers", "East", "Central"),
    "LAC": ("LA Clippers", "West", "Pacific"),
    "LAL": ("Los Angeles Lakers", "West", "Pacific"),
    "MEM": ("Memphis Grizzlies", "West", "Southwest"),
    "MIA": ("Miami Heat", "East", "Southeast"),
    "MIL": ("Milwaukee Bucks", "East", "Central"),
    "MIN": ("Minnesota Timberwolves", "West", "Northwest"),
    "NOP": ("New Orleans Pelicans", "West", "Southwest"),
    "NYK": ("New York Knicks", "East", "Atlantic"),
    "OKC": ("Oklahoma City Thunder", "West", "Northwest"),
    "ORL": ("Orlando Magic", "East", "Southeast"),
    "PHI": ("Philadelphia 76ers", "East", "Atlantic"),
    "PHX": ("Phoenix Suns", "West", "Pacific"),
    "POR": ("Portland Trail Blazers", "West", "Northwest"),
    "SAC": ("Sacramento Kings", "West", "Pacific"),
    "SAS": ("San Antonio Spurs", "West", "Southwest"),
    "TOR": ("Toronto Raptors", "East", "Atlantic"),
    "UTA": ("Utah Jazz", "West", "Northwest"),
    "WAS": ("Washington Wizards", "East", "Southeast"),
}

